import 'dotenv/config';
import { Client } from "@microsoft/microsoft-graph-client";
import { ClientSecretCredential } from "@azure/identity";

/**
 * Initialize Microsoft Graph Client
 */
function graphClient() {
  const credential = new ClientSecretCredential(
    process.env.TENANT_ID,
    process.env.CLIENT_ID,
    process.env.CLIENT_SECRET
  );

  return Client.initWithMiddleware({
    authProvider: {
      getAccessToken: async () => {
        const token = await credential.getToken("https://graph.microsoft.com/.default");
        return token.token;
      }
    }
  });
}

/**
 * Send Email via Microsoft Graph API
 */
async function sendGraphEmail(to, subject, html) {
  const client = graphClient();

  const email = {
    message: {
      subject,
      body: {
        contentType: "HTML",
        content: html,
      },
      toRecipients: [
        {
          emailAddress: { address: to }
        }
      ],
      from: {
        emailAddress: { address: process.env.EMAIL_USER }
      }
    }
  };

  await client.api(`/users/${process.env.EMAIL_USER}/sendMail`).post(email);
  return true;
}

/**
 * Send Verification Email
 */
export const sendVerificationEmail = async (email, code, firstName) => {
  try {
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #ddd; border-radius: 8px;">
        
        <h2 style="text-align: center; color: #333;">
          Email Test Successful
        </h2>

        <p>Hey <strong>${firstName}</strong>,</p>

        <p>
          This email confirms that the <strong>email sending functionality is working correctly</strong>.
        </p>

        <p>
          Below is a test verification code generated by the system:
        </p>

        <div style="
          background: #f4f4f4;
          padding: 20px;
          text-align: center;
          font-size: 28px;
          font-weight: bold;
          letter-spacing: 6px;
          margin: 30px 0;
          border-radius: 6px;
        ">
          ${code}
        </div>

        <p style="font-size: 14px; color: #666; text-align: center;">
          If you received this email, everything is working as expected 🚀
        </p>

        <hr style="margin: 30px 0;" />

        <p style="text-align: center; font-size: 13px; color: #999;">
          This is an automated test email.
        </p>
      </div>
    `;

    await sendGraphEmail(email, "Email Test – Verification", html);
    console.log(`Verification email sent → ${email}`);

    return true;
  } catch (error) {
    console.error("Verification email error:", error);
    return false;
  }
};


/**
 * Send Welcome Email
 */
export const sendWelcomeEmail = async (email, firstName) => {
  try {
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #ddd; border-radius: 8px;">
        
        <h2 style="text-align: center; color: #333;">
          🎉 Email System Working
        </h2>

        <p>Hey <strong>${firstName}</strong>,</p>

        <p>
          Great news! This message confirms that:
        </p>

        <ul>
          <li>The backend is running</li>
          <li>The frontend is communicating correctly</li>
          <li>Microsoft Graph email sending works</li>
        </ul>

        <p>
          If you are reading this email, the test was <strong>successful</strong> ✅
        </p>

        <hr style="margin: 30px 0;" />

        <p style="text-align: center; font-size: 13px; color: #999;">
          Sent via Node.js + Microsoft Graph
        </p>
      </div>
    `;

    await sendGraphEmail(email, "🎉 Email Test – Success", html);
    console.log(`Welcome email sent → ${email}`);

    return true;
  } catch (error) {
    console.error("Welcome email error:", error);
    return false;
  }
};

